[versions]
lib = "1.0.0"
agp = "8.13.2"
kotlin = "2.3.0"
osdetector = "1.7.3"
kotest = "6.0.3"
kotlinpoet = "2.2.0"
ksp = "2.3.4"
publish = "0.34.0"

[libraries]
kotest = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-framework = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }
kotest-property = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

[bundles]
kotest = [ "kotest", "kotest-framework", "kotest-property" ]

[plugins]
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
osdetector = { id = "com.google.osdetector", version.ref = "osdetector" }
kotest = { id = "io.kotest", version.ref = "kotest" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }