name: Test

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.txt'
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.txt'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            tasks: ":annotations:build :ksp:build :jni:allTests e2e:packageAndroidNatives e2e:assembleAndroidDeviceTest"
            jvm_heap: "-Xmx12g"
          - os: windows-latest
            tasks: ":jni:mingwX64Test"
            jvm_heap: "-Xmx12g"
          - os: macos-latest
            tasks: ":jni:macosArm64Test"
            jvm_heap: "-Xmx5g"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_CONFIGURATION_CACHE_KEY }}

      - name: cache kotlin-konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-kotlin-konan

      - name: Build and Test
        run: ./gradlew ${{ matrix.tasks }} :e2e:jvmTest
        continue-on-error: true
        env:
          GRADLE_OPTS: >-
            ${{ matrix.jvm_heap }}
            -Dorg.gradle.jvmargs="${{ matrix.jvm_heap }} -XX:+UseG1GC -XX:MaxMetaspaceSize=512m"
            -Dkotlin.daemon.jvm.options="-Xmx2048m"

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-${{ runner.os }}
          path: ./**/build/test-results/**/*.xml
          retention-days: 5

      # Now Android
      - name: Login to Google Cloud
        if: runner.os == 'Linux'
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Set current project
        if: runner.os == 'Linux'
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        if: ${{ runner.os }} == 'Linux'
        env:
          APP_DEBUG_LOCATION: e2e/build/outputs/apk/androidTest/e2e-androidTest.apk
          ANDROID_TEST_LOCATION: e2e/build/outputs/apk/androidTest/e2e-androidTest.apk
          DEVICE_MODEL: SmallPhone.arm,version=35
        run: gcloud firebase test android run \
          --type instrumentation \
          --app $APP_DEBUG_LOCATION \
          --test $ANDROID_TEST_LOCATION \
          --device model=$DEVICE_MODEL \
          --results-dir="run-${{ github.run_id }}" \
          --no-record-video
      - name: Download Results
        if: always() && runner.os == 'Linux'
        run: |
          mkdir -p firebase-results
          # Replace 'your-bucket-name' with your actual bucket (e.g. test-lab-xxxx)
          gsutil -m cp -r "gs://test-lab-duz7wkikhd4qa-n6cdwhda63m1u/run-${{ github.run_id }}/**/test_result_*.xml" ./firebase-results/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always() && runner.os == 'Linux'
        with:
          name: test-report-android
          path: firebase-results/
  publish-results:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Detailed Test Report Linux
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "Tests: Linux"
          path: "artifacts/test-report-Linux/**/*.xml"
          reporter: java-junit

      - name: Detailed Test Report Windows
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "Tests: Windows"
          path: "artifacts/test-report-Windows/**/*.xml"
          reporter: java-junit

      - name: Detailed Test Report MacOS
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "Tests: MacOS"
          path: "artifacts/test-report-macOS/**/*.xml"
          reporter: java-junit

      - name: Detailed Test Report Android
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "Tests: Android"
          path: "artifacts/test-report-android/**/*.xml"
          reporter: java-junit
