name: Test Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            tasks: ":annotations:build :ksp:build :jni:linuxX64Test"
          - os: windows-latest
            tasks: ":jni:mingwX64Test"
          - os: macos-latest
            tasks: ":jni:macosArm64Test"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_CONFIGURATION_CACHE_KEY }}
          gradle-home-cache-includes: |
            .konan/dependencies
            .konan/kotlin-native-prebuilt

      - name: Build and Test
        run: ./gradlew ${{ matrix.tasks }} :e2e:jvmTest
        continue-on-error: true

      - name: Upload :jni Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jvm-test-report
          path: jni/build/reports/tests/*/
          retention-days: 5

      - name: Upload :e2e Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-report-${{ runner.os }}
          path: e2e/build/reports/tests/*/
          retention-days: 5
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/build/test-results/**/*.xml"
          check_name: "Test Results (${{ runner.os }})"
          report_individual_runs: true
          deduplicate_classes_by_file_name: false